* RoboJackets Software Training [[https://circleci.com/gh/RoboJackets/software-training][file:https://circleci.com/gh/RoboJackets/software-training.svg?style=shield]]

This is the source repository for the 2018 RoboJackets Software training program.

# TODO this section needs to be redone/populated
* Slides

1. Week 1
   + [[https://robojackets.github.io/software-training/slides/week1/git.html][Git Presentation]]
   + [[https://robojackets.github.io/software-training/slides/week1/week1.html][Presentation]]

# TODO maybe host these MD files in an external way other than GH?
* Docs
1. Week 1
   + [[https://github.com/RoboJackets/software-training/blob/gh-pages/docs/week1/week1.md][Presentation]]


* Installation Instructions

I. Git
  A. Ubuntu: “sudo apt install git”
  B. All other OSes: https://git-scm.com/downloads 
    1. Install to the default location
    2. If it asks for a default text editor, choose something from the list that you know how to use. If you aren’t familiar with any of them, choose “nano”
    3. Leave all other options as the default
  C. To use Git in Linux or Mac, open a terminal. In Windows, you will need to launch the Git Bash program after you install it
II. Windows only: [[http://mingw.org/wiki/Getting_Started][MinGW]]
  A. Download mingw-get-setup.exe
  B. Leave the default installation location and related settings
  C. Mark base-bin and gcc-g++-bin for installation
  D. Installation -> apply
III. JetBrains CLion
  A. You can get a JetBrains student account for free, or use the 30-day trial for now
  B. Use the default install settings
  C. Make sure that the build/toolchain plugin can find your C++ compiler, C compiler, and “make” that you installed through MinGW
    1. If Windows Defender gets in the way of this, you may have to exclude MinGW from scanning and/or shut off Defender entirely :(


* Building Slides

1. Navigate to the ~./slides~ directory
2. Install [[https://github.com/cask/cask][cask]].
3. Run these commands
  #+BEGIN_SRC sh
  cask install
  make
  #+END_SRC
4. Output will be placed in the ~html/~ directory, at the root
